In [9]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import math
df=pd.read_csv("multiLinReg.csv")
df


area  Bedroom  Age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [10]:
median_Bedroom=math.floor(df.Bedroom.median())
median_Bedroom
df.Bedroom=df.Bedroom.fillna(median_Bedroom)
df


area  Bedroom  Age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [13]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','Bedroom','Age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [15]:
reg.intercept_

383724.99999999994

In [16]:
df

area  Bedroom  Age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [17]:
reg.predict([[3000,3,40]])

array([444400.])

In [19]:
reg.predict([[2500,4,5]])

array([588625.])